#!/bin/bash
#use inside git repo
#make sure that old fusemountpoint is unmounted (fusermount -u)
mountPoint=point
containerFile=container.bin
inputFiles=Test*
copyFiles=README.md
log=log.txt

cd $mountPoint/
rm *
echo testing max files
for i in `seq 64`; do
	touch test${i}.txt;
	echo $i >> test${i}.txt; 
done;
echo 64 files createtd
ls -l
echo test results press key to continiu
read -n 1 -s


echo testing mixed writing
rm *
touch file1.txt
touch file2.txt

for i in `seq 256`; do
	echo 12345678 >> file1.txt;
	echo 23456789 >> file2.txt;
done;
echo test complete press any key to finisch and clean up
read -n 1 -s
rm *
